# C44EsfLCim6gAfkHZEND0NDQPqJUGs9sXFIXcKPTpCTatlzqFlLaJQQJ99BDACAAAAAAAAAAAAASAZDOVHrS

trigger:
- '*'
#- main

pool:
  name: 'Default'
    #vmImage: ubuntu-latest
    
variables:
    buildConfiguration: 'Release'

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK 6.x'
      inputs:
        packageType: sdk
        version: '6.x'

    - script: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 16
        nvm use 16
        export PATH="$NVM_DIR/versions/node/v16.*/bin:$PATH"
        echo "Node.js version:"
        node -v
        echo "NPM version:"
        npm -v
      displayName: 'Use Node.js 16 and verify version'

    - script: |
        echo "Current PATH:"
        echo $PATH
        which node
        which npm
      displayName: 'Debug Node.js Environment'

    - script: 'rm -rf node_modules package-lock.json'
      displayName: 'Remove node_modules and package-lock.json'

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    # - script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
    #   displayName: 'Compile Sass assets'

    # - task: gulp@1
    #   displayName: 'Run gulp tasks'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info into file'
      workingDirectory: Tailspin.SpaceGame.Web/wwwroot

    - task: DotNetCoreCLI@2
      displayName: 'Restore .NET dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build .NET project'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--no-restore --configuration $(buildConfiguration)' # buildConfiguration is defined above in variables
