# C44EsfLCim6gAfkHZEND0NDQPqJUGs9sXFIXcKPTpCTatlzqFlLaJQQJ99BDACAAAAAAAAAAAAASAZDOVHrS

trigger:
- '*'
#- main

pool:
  name: 'Default'
    #vmImage: ubuntu-latest
    
variables:
    buildConfiguration: 'Release'

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK 6.x'
      inputs:
        packageType: sdk
        version: '6.x'

    - script: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 16
        nvm use 16
        export PATH="$NVM_DIR/versions/node/v16.*/bin:$PATH"
        node -v
        npm -v
        rm -rf node_modules package-lock.json
        npm cache clean --force
        export PYTHON=/opt/homebrew/bin/python3.11
        npm install
      displayName: 'Use Node.js 16 and verify version and try to install npm packages'

    - script: |
        echo "Current PATH:"
        echo $PATH
        which node
        which npm
        python3 --version
        which python3
      displayName: 'Debug Environment'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info into file'
      workingDirectory: Tailspin.SpaceGame.Web/wwwroot

    - task: DotNetCoreCLI@2
      displayName: 'Restore .NET dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build .NET project'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--no-restore --configuration $(buildConfiguration)' # buildConfiguration is defined above in variables
